INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Bosch', 'UniversalImpact 18V', 'Bohrmaschine', 2022, 1, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Makita', 'HR2470', 'Bohrhammer', 2020, 2, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('DeWalt', 'DCD771C2', 'Akku-Schrauber', 2021, 3, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Einhell', 'RT-OS 13', 'Schwingschleifer', 2023, 4, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Stihl', 'MS 170', 'Kettensäge', 2019, 5, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Husqvarna', 'Husqvarna 120i', 'Akku-Kettensäge', 2021, 6, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Gardena', 'Smart Sileno', 'Rasenmähroboter', 2022, 7, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Ryobi', 'R18AG', 'Winkelschleifer', 2020, 8, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Black+Decker', 'BDS181S1', 'Bohrschrauber', 2019, 9, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Fiskars', 'X27', 'Axt', 2022, 10, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Karcher', 'K4 Full Control', 'Hochdruckreiniger', 2020, 11, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Bosch', 'AdvancedVac 20', 'Staubsauger', 2021, 12, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('LUX', 'Tools LXT 32', 'Drehschlagschrauber', 2023, 13, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Einhell', 'BG-EC 1840', 'Elektrische Heckenschere', 2020, 14, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Makita', 'BUB360Z', 'Akku-Laubbläser', 2021, 15, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Triton', 'TRA001', 'Oberfräse', 2022, 16, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Worx', 'WG546E.9', 'Akku-Laubbläser', 2021, 17, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Bosch', 'PST 900 PEL', 'Stichsäge', 2020, 18, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Hilti', 'TE 7-C', 'Bohrhammer', 2019, 19, NULL, NULL);
INSERT INTO devices (brand, model, category, purchaseyear, id, borrower, returndate) VALUES ('Dewalt', 'DCB184-2', 'Akku', 2023, 20, NULL, NULL);